### ISSUE TITLE
EnvWrapper.py is missing

### ISSUE THREAD

**Issue by lvisdd** [liuanji/WU-UCT#1]
Could you share the EnvWrapper file with us?
[./Env/EnvWrapper.py](https://github.com/liuanji/WU-UCT/tree/master/Env/EnvWrapper.py)

**Comment by liuanji** [comment]
Updated. Sorry it was ignored by the .gitignore file

**Comment by liuanji** [comment]
Please pull the latest code (also added an empty Log/ folder for output logs), I have tested on my computer and it should work. Sorry about the mistake.

**Comment by lvisdd** [comment]
Thanks.
I can run your code on Google Colaboratory.

```
pip install torch==1.0.1
mkdir -p ./Logs
mkdir -p ./Records
mkdir -p ./Results
python3 main.py --model WU-UCT --env-name PongNoFrameskip-v0 --max-episode-length 100 --record-video
```

https://colab.research.google.com/drive/140Ea6pd8abvg_HdZDVsCVfdeLICSa-f0

**Comment by liuanji** [comment]
@lvisdd Thank you for providing such a useful demo! Would you mind if I put the Google Colaboratory link in Readme.md? I think it would a great help for others who want to run the code. I will claim your authorship on the demo.

Again thank you for your interest in our work and all the efforts you have done to help us improve it!

**Comment by lvisdd** [comment]
@liuanji Sure, no problem.
Thank you very much for your great work.
