### ISSUE TITLE
how to parallel simulation on muiti-gpus

### ISSUE THREAD

**Issue by YYangZiXin** [liuanji/WU-UCT#3]

**Comment by YYangZiXin** [comment]
in my case, calculating reward cost much time , so i want to calculate reward on muiti-gpus when simulation

**Comment by liuanji** [comment]
If you are using neural networks as policy, you can add ``--device cuda'' argument to use multiple GPUs to compute the policy during simulation. However, since the Atari simulator can only run on CPUs, that part of the simulation step cannot utilize multiple GPUs.

**Comment by YYangZiXin** [comment]
thanks
