### ISSUE TITLE
The program cannot exit normally.

### ISSUE THREAD

**Issue by shibei00** [liuanji/WU-UCT#4]
When I run the following commands 

"python3 main.py --model WU-UCT --env-name PongNoFrameskip-v0 --MCTS-max-steps 10 --max-episode-length 3 --simulation-worker-num 2  --expansion-worker-num 2", the main process will be blocked at MCTStree.close() method. The workers cannot be terminated normally.

**Comment by liuanji** [comment]
Hi,

Thanks for reporting the issue. The problem was resolved in the latest commit.
